kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-persistent-vol
  labels:
    type: local
    app: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/data"