kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-vol-claim
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
