apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: local
    http:
      paths:
      - path: /mongo
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service
            port: 
              number: 8081
      - path: /sqlpad
        pathType: Prefix
        backend:
          service:
            name: sqlpad-service
            port:
              number: 3000
      - path: /mongodb
        pathType: Prefix
        backend:
          service:
            name: mongodb-ext-service
            port:
              number: 27017
      - path: /redis
        pathType: Prefix
        backend:
          service:
            name: redis-service
            port:
              number: 6379