apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: local
    http:
      paths:
      
      # - path: /pgadmin
      #   backend:
      #     serviceName: pgadmin-service
      #     servicePort: 5050
      # - path: /mongoadmin
      #   backend:
      #     serviceName: mongo-express-service
      #     servicePort: 8081
      # - path: /pyapi
      #   backend:
      #     serviceName: fullstack-backend
      #     servicePort: 5000