apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: local
    http:
      paths:
      - path: /mongo
        pathType: Prefix
        backend:
          service:
            name: mongo-express-service
            port: 
              number: 8081
      - path: /sqlpad
        pathType: Prefix
        backend:
          service:
            name: sqlpad-service
            port:
              number: 3000