kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-persistent-vol
  labels:
    type: local
    app: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-vol-claim
  labels:
    app: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
