apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 8080
    nodePort: 30005
