apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4008
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password
          - name: MARIADB_DATABASE
            value: main
        volumeMounts:
          - mountPath: /var/lib/mariadb/data
            name: mariadb-volume
      volumes:
        - name: mariadb-volume
          persistentVolumeClaim:
            claimName: mariadb-vol-claim