kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-persistent-vol
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mariadb/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-vol-claim
  labels:
    app: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi